### ISSUE TITLE
Spacing after code chunks?

### ISSUE THREAD

**Issue by apreshill** [rstudio4edu/fancy-book-demo#3]
Noticing with the style that sometimes the next para after a code chunk looks pretty squished...

<img width="793" alt="Screen Shot 2019-09-02 at 9 02 58 PM" src="https://user-images.githubusercontent.com/12160301/64143537-5a5ff400-cdc5-11e9-9b96-074767896342.png">

**Comment by dcossyleon** [comment]
Oops, I should have included an additional style rule when I fixed the symmetry: 

```
.sourceCode {
  margin-bottom: 0.85em; /* adds same amount of margin as a <p> would */
}
```
